name: CarryOnMobs
version: 1.0.0
main: me.leonohnex.carryOnPlugin.CarryOnPlugin
api-version: 1.21
author: LeonOhneX
description: Ein Plugin zum Tragen von Mobs - inspiriert von der CarryOn Mod

commands:
  carryreload:
    description: Lädt das CarryOn Mob Plugin neu
    usage: /carryreload
    permission: carryon.reload

permissions:
  carryon.entity:
    description: Erlaubt das Tragen von Mobs/Entities
    default: true
  carryon.reload:
    description: Erlaubt das Neuladen des Plugins
    default: op